name: build_and_publish_container 

on:
  push:
    branches: [ main ]

  pull_request:
    branches:  none 

  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: latest

jobs:
    
  build_container:
  
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
          
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3


    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to registry ${{ env.REGISTRY }}
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v1
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        
    - name: Build and publish Docker image
      id: build-and-push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        labels: ${{ steps.meta.outputs.labels }}
        

